# Generated by Django 5.2.8 on 2025-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
