# Generated by Django 5.2.8 on 2026-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cliente_direccion_cliente_created_at_and_more'),
        ('ventas', '0002_alter_lineapedido_precio_unitario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineapedido',
            name='cantidad_positiva',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción (Snapshot)'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='tipo_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.21, max_digits=4, verbose_name='IVA Aplicado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha'], name='idx_pedido_cliente_fecha'),
        ),
        migrations.AddConstraint(
            model_name='lineapedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_linea_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total_neto__gte', 0)), name='total_pedido_positivo'),
        ),
    ]
