# Generated by Django 5.2.14 on 2026-05-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_cliente_direccion_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etapa', models.CharField(choices=[('PRO', 'Prospección'), ('PRP', 'Propuesta'), ('NEG', 'Negociación'), ('GAN', 'Cerrada Ganada'), ('PER', 'Cerrada Perdida')], default='PRO', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
